### ISSUE TITLE
Adding Files as a type on reliquery.

### ISSUE THREAD

**Issue by ibebrett** [The-Dev-Effect/reliquery#38]
It would be great to be able to save arbitrary files onto relics when there is no matching type (like array or dataframe). 

Right now there are internal methods for adding binary objects, but it would be convenient to use them from public interfaces. 

Since a file is pretty much represented by paths, it would be cool for it to have interfaces like:

```
rq.add_file_from_path(name: str, path: str)
rq.list_files()
rq.save_file_to_path(name: str, path: str)
rq.get_file(name: str) -> File like object.
```

It would be awesome if the UI could display the list of those files, as well as have a UI element that allows downloading of those files.

**Comment by AntiAnt** [comment]
added an issue in reliquery-ui https://github.com/The-Dev-Effect/reliquery-ui/issues/25
