### ISSUE TITLE
Image data improvements

### ISSUE THREAD

**Issue by AntiAnt** [The-Dev-Effect/reliquery#39]
**Is your feature request related to a problem? Please describe.**
Improvements to saving images including: 
- add image from path 
- clean up current add image to take file like object instead of current method
- Save image/plot in the previously run notebook cell

**Describe the solution you'd like**
Add new methods:
```python
rq.add_image_from_path(name: str, path: str)
rq.save_image_to_path(name: str, path: str)
rq.add_last_image(name: str, image: ?)
```
update old methods:
```python
rq.add_image(name: str, image: File Like Object)
```

**Comment by Jacquelinet19** [comment]
Hold off on add_last_image method, but will take care of the rest
