### ISSUE TITLE
Removing relics does not translate to UI. Relics deleted still show in UI tables.

### ISSUE THREAD

**Issue by AntiAnt** [The-Dev-Effect/reliquery#62]
# Reliquery Issue Report
Thank you for raising our awareness of an Issue with Reliquery. Before submitting this Issue report check and make sure there aren't any duplicate Issues currently open. Please give as much detail about the issue as you can to help us try and resolve it.

## Prerequisites

- [x] Are you running the latest version?

## Description of Issue
Removing relics does not translate to UI. Relics deleted still show in UI tables.
## Expected Behavior
Deleting relics and data would not show on the UI.

## Actual Behavior
They continue to persist

## Steps to Reproduce the Problem

  1. delete relic that exists in demo bucket
  1. hosted UI still shows the relic
  1.

## Possible Solution
Logic that updates database when relics are no longer available correctly.

**Comment by AntiAnt** [comment]
You can now remove old stale relics that have been deleted buy syncing reliquery.

**Comment by Jacquelinet19** [comment]
#77
